# Inspired from https://github.com/htr3n/zsh-config

# https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zshenv
# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

path=(~/.local/bin $path)

if [[ -d "$HOME/.scripts" ]]; then
    path=("$HOME/.scripts" $path)
fi

# eliminates duplicates in *paths
typeset -gU cdpath fpath path
